(TeX-add-style-hook
 "ml"
 (lambda ()
   (setq TeX-command-extra-options
         "-shell-escape")
   (add-to-list 'LaTeX-verbatim-environments-local "minted")
   (add-to-list 'LaTeX-verbatim-environments-local "cppcode")
   (add-to-list 'LaTeX-verbatim-environments-local "cppcode*")
   (add-to-list 'LaTeX-verbatim-environments-local "latexcode")
   (add-to-list 'LaTeX-verbatim-environments-local "latexcode*")
   (add-to-list 'LaTeX-verbatim-environments-local "javacode")
   (add-to-list 'LaTeX-verbatim-environments-local "javacode*")
   (add-to-list 'LaTeX-verbatim-environments-local "cudacode")
   (add-to-list 'LaTeX-verbatim-environments-local "cudacode*")
   (add-to-list 'LaTeX-verbatim-environments-local "bashcode")
   (add-to-list 'LaTeX-verbatim-environments-local "bashcode*")
   (add-to-list 'LaTeX-verbatim-environments-local "tcshcode")
   (add-to-list 'LaTeX-verbatim-environments-local "tcshcode*")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "cppinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "latexinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "javainline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "cudainline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "pythoninline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "tcshinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "bashinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "sql")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "Rinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "cppinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "latexinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "javainline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "cudainline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "pythoninline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "tcshinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "bashinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "sql")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Rinline")
   (TeX-run-style-hooks
    "ml_submodule/src/assesment_and_selection/intro"
    "ml_submodule/src/assesment_and_selection/generalization_error"
    "ml_submodule/src/assesment_and_selection/expected_risk_minimizer"
    "ml_submodule/src/assesment_and_selection/empirical_risk"
    "ml_submodule/src/assesment_and_selection/empirical_risk_minimizer"
    "ml_submodule/src/assesment_and_selection/squared_loss/squared_loss"
    "ml_submodule/src/assesment_and_selection/bayes_optimal_predictor"
    "ml_submodule/src/assesment_and_selection/cross_validation/cross_validation"
    "ml_submodule/src/assesment_and_selection/data/labeled_data"
    "ml_submodule/src/assesment_and_selection/data/traing_set"
    "ml_submodule/src/assesment_and_selection/data/traing_error"
    "ml_submodule/src/assesment_and_selection/data/testing_set"
    "ml_submodule/src/assesment_and_selection/data/test_error"
    "ml_submodule/src/assesment_and_selection/data/validation_set"
    "ml_submodule/src/assesment_and_selection/validation_set_approach"
    "ml_submodule/src/assesment_and_selection/cross_validation/leave_one_out/leave_one_out"
    "ml_submodule/src/assesment_and_selection/cross_validation/leave_one_out/squared_error"
    "ml_submodule/src/assesment_and_selection/cross_validation/kfold/kfold"
    "ml_submodule/src/assesment_and_selection/cross_validation/kfold/many_random_devisions"
    "ml_submodule/src/statistical_perspective/information_theory/self_information"
    "ml_submodule/src/statistical_perspective/information_theory/entropy"
    "ml_submodule/src/statistical_perspective/information_theory/conditional_entropy"
    "ml_submodule/src/statistical_perspective/information_theory/cross_entropy"
    "ml_submodule/src/statistical_perspective/information_theory/kullback_leibler_divergence"
    "ml_submodule/src/statistical_perspective/information_theory/mutual_information"
    "ml_submodule/src/assesment_and_selection/proofs"
    "ml_submodule/src/assesment_and_selection/squared_loss/proofs"
    "ml_submodule/src/statistical_perspective/proofs"
    "ml_submodule/src/statistical_perspective/examples"
    "ml_submodule/src/assesment_and_selection/examples"
    "ml_submodule/src/statistical_perspective/supervised_learning"
    "ml_submodule/src/statistical_perspective/estimators"
    "ml_submodule/src/glm/glm"
    "ml_submodule/src/gam/gam"
    "ml_submodule/src/regression/regression"
    "ml_submodule/src/regression/linear/simple_regression"
    "ml_submodule/src/regression/linear/multiple_regression"
    "ml_submodule/src/regression/linear/existence"
    "ml_submodule/src/regression/ordinary_least_squares/ordinary_least_squares"
    "ml_submodule/src/regression/ordinary_least_squares/mle/mle"
    "ml_submodule/src/regression/ordinary_least_squares/normal_equation/normal_equation"
    "ml_submodule/src/regression/ordinary_least_squares/normal_equation/geometric_interpretation"
    "ml_submodule/src/regression/ordinary_least_squares/normal_equation/solution"
    "ml_submodule/src/regression/ordinary_least_squares/normal_equation/cholesky_decomposition"
    "ml_submodule/src/regression/ordinary_least_squares/solution"
    "ml_submodule/src/regression/ordinary_least_squares/normal_equation/predictions"
    "ml_submodule/src/regression/ordinary_least_squares/normal_equation/uniqueness"
    "ml_submodule/src/regression/ordinary_least_squares/moments/betahat"
    "ml_submodule/src/regression/ordinary_least_squares/moments/yhat"
    "ml_submodule/src/regression/ordinary_least_squares/moments/residuals"
    "ml_submodule/src/regression/ordinary_least_squares/moments/stdhat"
    "ml_submodule/src/regression/ordinary_least_squares/gauss_markov_theorem"
    "ml_submodule/src/gaussian_process/linear_regression"
    "ml_submodule/src/regression/ordinary_least_squares/mle/tmp"
    "ml_submodule/src/regression/linear/proofs"
    "ml_submodule/src/regression/ordinary_least_squares/moments/proofs"
    "ml_submodule/src/regression/linear/examples"
    "ml_submodule/src/supervised_learning/classification/intro"
    "ml_submodule/src/supervised_learning/classification/binary_classification/binary_classification"
    "ml_submodule/src/supervised_learning/classification/categorical_multiclass_classification/categorical_multiclass_classification"
    "ml_submodule/src/supervised_learning/classification/one_hot_encoding"
    "ml_submodule/src/supervised_learning/classification/soft_hard_labels"
    "ml_submodule/src/supervised_learning/classification/binary_classification/linear_dichotomy"
    "ml_submodule/src/supervised_learning/classification/binary_classification/linear_classifier"
    "ml_submodule/src/supervised_learning/classification/binary_classification/classification_criterion"
    "ml_submodule/src/supervised_learning/classification/binary_classification/normalization"
    "ml_submodule/src/classification/logistic_regression/intro"
    "ml_submodule/src/classification/logistic_regression/logistic_function"
    "ml_submodule/src/classification/logistic_regression/logistic_regression"
    "ml_submodule/src/classification/logistic_regression/logistic_loss"
    "ml_submodule/src/classification/logistic_regression/map"
    "ml_submodule/src/classification/proofs"
    "ml_submodule/src/glm/gam/gam"
    "ml_submodule/src/glm/gam/backfitting"
    "ml_submodule/src/mle/intro"
    "ml_submodule/src/mle/mle"
    "ml_submodule/src/map/intro"
    "ml_submodule/src/map/prior"
    "ml_submodule/src/map/posterior"
    "ml_submodule/src/map/maximization"
    "ml_submodule/src/map/proofs"
    "ml_submodule/src/map/examples"
    "ml_submodule/src/bayesian_inference/intro"
    "ml_submodule/src/bayesian_inference/epistemic_uncertainty"
    "ml_submodule/src/bayesian_inference/aleatoric_uncertainty"
    "ml_submodule/src/bayesian_inference/bayesian_filtering/intro"
    "ml_submodule/src/bayesian_inference/bayesian_filtering/kalman_filter"
    "ml_submodule/src/bayesian_inference/gaussian_processes/linear_regression"
    "ml_submodule/src/bayesian_inference/gaussian_processes/kernelized_linear_regression"
    "ml_submodule/src/bayesian_inference/gaussian_processes/gp"
    "ml_submodule/src/bayesian_inference/approximate_inference/intro"
    "ml_submodule/src/bayesian_inference/approximate_inference/variational_inference/intro"
    "ml_submodule/src/bayesian_inference/approximate_inference/variational_inference/laplace_approximation"
    "ml_submodule/src/bayesian_inference/approximate_inference/variational_inference/kl_divergence"
    "ml_submodule/src/bayesian_inference/approximate_inference/variational_inference/elbo"
    "ml_submodule/src/bayesian_inference/approximate_inference/variational_inference/reparameterization_trick"
    "ml_submodule/src/bayesian_inference/approximate_inference/mcmc"
    "ml_submodule/src/bayesian_inference/approximate_inference/inla/inla"
    "ml_submodule/src/bayesian_inference/approximate_inference/variational_inference/bnn/intro"
    "ml_submodule/src/bayesian_inference/approximate_inference/variational_inference/bnn/map"
    "ml_submodule/src/bayesian_inference/approximate_inference/variational_inference/bnn/variational_inference"
    "ml_submodule/src/bayesian_inference/approximate_inference/variational_inference/bnn/making_predictions"
    "ml_submodule/src/bayesian_inference/proofs"
    "ml_submodule/src/bayesian_inference/examples"
    "ml_submodule/src/kernels/intro"
    "ml_submodule/src/kernels/kernels"
    "ml_submodule/src/kernels/gram_matrix"
    "ml_submodule/src/kernels/mercer"
    "ml_submodule/src/kernels/kernel_trick"
    "ml_submodule/src/kernels/types_of_kernels"
    "ml_submodule/src/kernels/linear"
    "ml_submodule/src/kernels/polynomial"
    "ml_submodule/src/kernels/sigmoid"
    "ml_submodule/src/kernels/exponential"
    "ml_submodule/src/kernels/gaussian"
    "ml_submodule/src/kernels/matern"
    "ml_submodule/src/kernels/kernel_engineering"
    "ml_submodule/src/kernels/proofs"
    "ml_submodule/src/kernels/examples"
    "ml_submodule/src/time_series/state_space_models/state_space_models"
    "ml_submodule/src/time_series/markov_models/foundations"
    "ml_submodule/src/time_series/markov_models/markov_chains/markov_chains"
    "ml_submodule/src/time_series/markov_models/markov_chains/characteristics"
    "ml_submodule/src/time_series/markov_models/markov_chains/types"
    "ml_submodule/src/time_series/markov_models/markov_chains/mcmc"
    "ml_submodule/src/time_series/markov_models/proofs"
    "ml_submodule/src/time_series/markov_models/examples"
    "ml_submodule/src/time_series/markov_models/hidden_markov_model/hidden_markov_model"
    "ml_submodule/src/time_series/markov_models/markov_decision_processes/intro"
    "ml_submodule/src/time_series/markov_models/markov_decision_processes/policies_and_values"
    "ml_submodule/src/time_series/markov_models/markov_decision_processes/value"
    "ml_submodule/src/time_series/markov_models/markov_decision_processes/policies"
    "ml_submodule/src/time_series/markov_models/markov_decision_processes/greedy_policies"
    "ml_submodule/src/time_series/markov_models/markov_decision_processes/bellman_equation"
    "ml_submodule/src/time_series/markov_models/markov_decision_processes/policy_iteration"
    "ml_submodule/src/time_series/markov_models/markov_decision_processes/value_iteration"
    "ml_submodule/src/time_series/markov_models/partially_observable_markov_decision_processes/partially_observable_markov_decision_processes"
    "ml_submodule/src/time_series/markov_models/partially_observable_markov_decision_processes/mpds"
    "ml_submodule/src/time_series/markov_models/markov_decision_processes/proofs"
    "ml_submodule/src/time_series/markov_models/partially_observable_markov_decision_processes/proofs"
    "ml_submodule/src/reinforcement_learning/reinforcement_learning"
    "ml_submodule/src/reinforcement_learning/on_policy"
    "ml_submodule/src/reinforcement_learning/off_policy"
    "ml_submodule/src/reinforcement_learning/trajectory"
    "ml_submodule/src/reinforcement_learning/model_based/model_based"
    "ml_submodule/src/reinforcement_learning/model_based/estimating"
    "ml_submodule/src/reinforcement_learning/model_based/explotation_vs_exploration"
    "ml_submodule/src/reinforcement_learning/model_based/epsilon_greedy"
    "ml_submodule/src/reinforcement_learning/model_based/rmax/rmax"
    "ml_submodule/src/reinforcement_learning/model_based/rmax/number_of_steps"
    "ml_submodule/src/reinforcement_learning/model_free/model_free"
    "ml_submodule/src/reinforcement_learning/model_free/temporal_difference_learning"
    "ml_submodule/src/reinforcement_learning/proofs"
    "ml_submodule/src/graph_theory/graph"
    "ml_submodule/src/graph_theory/vertices"
    "ml_submodule/src/graph_theory/vertices/adjacency_matrix"
    "ml_submodule/src/graph_theory/vertices/degree"
    "ml_submodule/src/graph_theory/edges"
    "ml_submodule/src/graph_theory/subgraph"
    "ml_submodule/src/graph_theory/components"
    "ml_submodule/src/graph_theory/walks/walk"
    "ml_submodule/src/graph_theory/walks/path"
    "ml_submodule/src/graph_theory/walks/cycle"
    "ml_submodule/src/graph_theory/graphs/weighted_graph"
    "ml_submodule/src/graph_theory/graphs/spanning/spanning"
    "ml_submodule/src/graph_theory/graphs/spanning/minimum_spanning"
    "ml_submodule/src/graph_theory/connected_graphs/connected_graphs"
    "ml_submodule/src/graph_theory/connected_graphs/fully_connected_graphs"
    "ml_submodule/src/graph_theory/directed_graphs/directed_graphs"
    "ml_submodule/src/graph_theory/acyclic_graphs/acyclic_graphs"
    "ml_submodule/src/graph_theory/acyclic_graphs/forests"
    "ml_submodule/src/graph_theory/acyclic_graphs/trees"
    "ml_submodule/src/graph_theory/layered_graph/layered_graph"
    "ml_submodule/src/graph_theory/spectral_decomposition/graph_laplacian")
   (LaTeX-add-labels
    "sec:numerical_estimation_statistic"
    "subsec:generalization_error"
    "subsubsubsec:expected_risk_minimizer"
    "subsubsubsec:empirical_risk_minimizer"
    "subsubsec:squared_loss"
    "subsec:cross_validation"
    "subsubsec:training_set"
    "subsubsec:testing_set"
    "subsubsec:validation_set"
    "subsec:hold_out_validation_set_validation"
    "subsec:leave-one-out_cross_validation_LOOCV"
    "subsubsubsec:loocv_for_squared_loss_and_lin._operator"
    "subsubsec:k-fold_cross_validation"
    "subsubsubsec:many_random_divisions"
    "section:statistical_perspective"
    "subsec:information_theory"
    "subsubsec:entropy"
    "subsubsubsec:conditonal_entropy"
    "subsubsec:cross_entropy"
    "subsubsec:mutual_information"
    "subsec:proofs"
    "subsec:examples"
    "sec:supervised_learning"
    "subsec:estimators"
    "sec:generalized_linear_models"
    "sec:regression"
    "subsec:simple_linear_squares"
    "subsec:multiple_linear_regression"
    "subsubsubsec:existence"
    "subsec:linear_ordinary_least_squares"
    "subsubsec:maximum_likelihood_estimate"
    "subsubsubsec:the_normal_equation"
    "subsubsubsec:solving_the_normal_equation"
    "subsec:simple_linear_regression_solution"
    "subsubsubsec:making_predictions"
    "subsubsec:moments_and_distributions"
    "subsubsubsec:the_gaus_markov_theorem"
    "subsec:maximum_likilihood"
    "sec:classification"
    "subsubsec:name"
    "subsubsec:types_of_classification"
    "subsubsec:encodings"
    "subsubsubsec:one_hot_encoding"
    "subsubsubsec:soft_vs_hard_labels"
    "subsec:binary_classification"
    "subsubsec:binary_linear_classification"
    "subsubsubsec:normalization"
    "subsec:logistic_regression"
    "subsubsec:logistic_function"
    "subsubsec:lg"
    "subsubsubsec:maximum_likelihood_estimate_logistic_rergression"
    "subsubsubsec:maximum_aposteriori_estimate_logistic_rergression"
    "sec:generalized_linear_model_glm"
    "subsec:generalized_additive_model_gam"
    "subsubsec:backfitting"
    "sec:model_parameter_estimation"
    "subsec:maximum_likelihood_estimation"
    "subsubsec:likelihood_function"
    "subsubsec:maximum_likelihood_estimation_mle"
    "subsec:maximum_a_posteriori_estimation"
    "subsubsec:prior_distribution"
    "subsubsec:posterior_distribution"
    "subsubsubsec:maximization_--_map"
    "sec:bayesian_inference"
    "subsec:types_of_uncertainty"
    "sec:bayesian_filtering"
    "subsec:kalman_filters"
    "sec:gaussian_processes"
    "subsec:gaussian_process_regression"
    "subsubsec:gaussian_linear_regression"
    "subsubsec:kernalized_gaussian_linear_regression"
    "subsubsec:marginal_likelihood"
    "sec:approximate_inference"
    "subsec:variational_inference"
    "subsubsec:laplace_approximation"
    "subsubsec:black_box_stochastic_variational_inference"
    "subsubsec:elbo"
    "subsubsec:the_reparameterization_trick"
    "subsec:markov_chain_monte_carlos_methods"
    "subsec:integrated_nested_laplace_approximation"
    "subsec:bayesian_neural_networks"
    "subsubsubsec:map_estimates_for_bnn"
    "subsubsec:variational_inference_for_bnn"
    "subsubsec:making_predictions"
    "sec:kernels"
    "subsec:the_gram_matrix"
    "subsec:mercers_theorem"
    "subsec:the_kernel_trick"
    "subsec:types_of_kernels"
    "subsec:important_kernels"
    "subsubsec:the_linear_kernel"
    "subsubsec:the_polynomial_kernel"
    "subsubsec:the_sigmoid_kernel"
    "subsubsec:the_exponential_kernel"
    "subsubsec:the_gaussian_kernel"
    "subsubsec:the_matern_kernel"
    "subsec:kernel_engineering"
    "sec:time_series"
    "sec:markov_chains"
    "subsec:markov_chains"
    "subsubsec:types_of_markov_chains"
    "subsec:markov_chain_monte_carlo_mcmc"
    "sec:hidden_markov_model"
    "sec:markov_decision_processes"
    "subsec:policies"
    "subsubsec:calculating_the_value_of_V"
    "subsubsec:choosing_the_policy"
    "subsubsubsec:greedy_policy"
    "subsubsubsec:policy_iteration"
    "subsubsubsec:value_iteration"
    "sec:partially_observable_markov_decision_processes"
    "subsec:pomdps_as_mdps"
    "sec:reinforcement_learning"
    "subsec:model_based_reinforcement_learning"
    "subsubsec:estimating_transitions_and_rewards"
    "subsubsec:reinforcement_epsilonc_greedy_algorithm"
    "subsubsec:reinforcement_rmax_algorithm"
    "subsubsubsec:how_many_transitions_do_we_need?"
    "subsubsec:temporal_difference_learning_td"
    "subsubsec:q-learning"
    "defn:action_value_function"
    "subsubsubsec:policy_gradients"
    "subsubsubsec:actor-critic_methods"
    "sec:graph_theory"
    "subsec:vertices"
    "subsec:edges"
    "subsubsec:subgraph"
    "subsubsec:component"
    "subsec:walks,_paths_and_cycles"
    "subsec:different_kinds_of_graphs"
    "subsec:weighted_graph"
    "subsec:spanning_graphs"
    "subsubsec:minimum_spanning_graph"
    "subsec:connected_graphs"
    "subsubsec:fully_connected"
    "subsubsec:directed_graphs"
    "subsubsec:trees_and_forest"
    "subsubsec:tree_acyclic_graphs"
    "bsubsec:graph_layering"
    "subsec:bisection_algorithms"
    "subsubsec:global_approaches"
    "subsubsec:spectral_decomposition"
    "subsubsubsec:inertial_bisection"))
 :latex)

